/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type LutExtended = {
  wrapper: Address;
  addressesAdded: number;
  totalAddresses: number;
  isReady: boolean;
  slotsUntilReady: bigint;
};

export type LutExtendedArgs = {
  wrapper: Address;
  addressesAdded: number;
  totalAddresses: number;
  isReady: boolean;
  slotsUntilReady: number | bigint;
};

export function getLutExtendedEncoder(): FixedSizeEncoder<LutExtendedArgs> {
  return getStructEncoder([
    ["wrapper", getAddressEncoder()],
    ["addressesAdded", getU32Encoder()],
    ["totalAddresses", getU32Encoder()],
    ["isReady", getBooleanEncoder()],
    ["slotsUntilReady", getU64Encoder()],
  ]);
}

export function getLutExtendedDecoder(): FixedSizeDecoder<LutExtended> {
  return getStructDecoder([
    ["wrapper", getAddressDecoder()],
    ["addressesAdded", getU32Decoder()],
    ["totalAddresses", getU32Decoder()],
    ["isReady", getBooleanDecoder()],
    ["slotsUntilReady", getU64Decoder()],
  ]);
}

export function getLutExtendedCodec(): FixedSizeCodec<
  LutExtendedArgs,
  LutExtended
> {
  return combineCodec(getLutExtendedEncoder(), getLutExtendedDecoder());
}
