/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { LUTS_PROGRAM_ADDRESS } from "../programs";

/** InvalidLookupTable: Invalid Lookup Table address */
export const LUTS_ERROR__INVALID_LOOKUP_TABLE = 0x1770; // 6000
/** LutNotReady: LUT not yet ready for use (cooldown period) */
export const LUTS_ERROR__LUT_NOT_READY = 0x1771; // 6001
/** MaxAddressesExceeded: Maximum addresses exceeded (256 limit) */
export const LUTS_ERROR__MAX_ADDRESSES_EXCEEDED = 0x1772; // 6002

export type LutsError =
  | typeof LUTS_ERROR__INVALID_LOOKUP_TABLE
  | typeof LUTS_ERROR__LUT_NOT_READY
  | typeof LUTS_ERROR__MAX_ADDRESSES_EXCEEDED;

let lutsErrorMessages: Record<LutsError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  lutsErrorMessages = {
    [LUTS_ERROR__INVALID_LOOKUP_TABLE]: `Invalid Lookup Table address`,
    [LUTS_ERROR__LUT_NOT_READY]: `LUT not yet ready for use (cooldown period)`,
    [LUTS_ERROR__MAX_ADDRESSES_EXCEEDED]: `Maximum addresses exceeded (256 limit)`,
  };
}

export function getLutsErrorMessage(code: LutsError): string {
  if (process.env.NODE_ENV !== "production") {
    return (lutsErrorMessages as Record<LutsError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isLutsError<TProgramErrorCode extends LutsError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    LUTS_PROGRAM_ADDRESS,
    code,
  );
}
